from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphWindow(object):
    def setupUi(self, GraphWindow):
        GraphWindow.setObjectName("GraphWindow")
        GraphWindow.resize(821, 645)
        self.centralwidget = QtWidgets.QWidget(GraphWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setMinimumSize(QtCore.QSize(0, 110))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tempLabel = QtWidgets.QLabel(self.frame)
        self.tempLabel.setMinimumSize(QtCore.QSize(86, 0))
        self.tempLabel.setText("")
        self.tempLabel.setScaledContents(True)
        self.tempLabel.setWordWrap(True)
        self.tempLabel.setObjectName("tempLabel")
        self.gridLayout_3.addWidget(self.tempLabel, 1, 1, 1, 1)
        self.runInfo = QtWidgets.QLabel(self.frame)
        self.runInfo.setText("")
        self.runInfo.setScaledContents(True)
        self.runInfo.setWordWrap(True)
        self.runInfo.setObjectName("runInfo")
        self.gridLayout_3.addWidget(self.runInfo, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.graphArea = CustomGraph(self.centralwidget)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.graphArea.setBackgroundBrush(brush)
        self.graphArea.setObjectName("graphArea")
        self.gridLayout.addWidget(self.graphArea, 0, 0, 1, 1)
        GraphWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(GraphWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setMinimumSize(QtCore.QSize(500, 0))
        self.toolBar.setObjectName("toolBar")
        GraphWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(GraphWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 821, 22))
        self.menuBar.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.menuBar.setFont(font)
        self.menuBar.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.menuBar.setObjectName("menuBar")
        self.menuGraph = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.menuGraph.setFont(font)
        self.menuGraph.setObjectName("menuGraph")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.menuView.setFont(font)
        self.menuView.setObjectName("menuView")
        self.menuMode = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.menuMode.setFont(font)
        self.menuMode.setObjectName("menuMode")
        GraphWindow.setMenuBar(self.menuBar)
        self.actionFit = QtWidgets.QAction(GraphWindow)
        self.actionFit.setObjectName("actionFit")
        self.actionPlot = QtWidgets.QAction(GraphWindow)
        self.actionPlot.setObjectName("actionPlot")
        self.actionLimiter = QtWidgets.QAction(GraphWindow)
        self.actionLimiter.setCheckable(True)
        self.actionLimiter.setChecked(False)
        self.actionLimiter.setObjectName("actionLimiter")
        self.actionClipper = QtWidgets.QAction(GraphWindow)
        self.actionClipper.setCheckable(True)
        self.actionClipper.setObjectName("actionClipper")
        self.actionClip = QtWidgets.QAction(GraphWindow)
        self.actionClip.setObjectName("actionClip")
        self.actionDielectric = QtWidgets.QAction(GraphWindow)
        self.actionDielectric.setCheckable(True)
        self.actionDielectric.setChecked(True)
        self.actionDielectric.setObjectName("actionDielectric")
        self.actionVFT_Arrhenius = QtWidgets.QAction(GraphWindow)
        self.actionVFT_Arrhenius.setCheckable(True)
        self.actionVFT_Arrhenius.setObjectName("actionVFT_Arrhenius")
        self.actionClear = QtWidgets.QAction(GraphWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.actionClear.setFont(font)
        self.actionClear.setObjectName("actionClear")
        self.actionSelected_Only = QtWidgets.QAction(GraphWindow)
        self.actionSelected_Only.setCheckable(True)
        self.actionSelected_Only.setObjectName("actionSelected_Only")
        self.actionDefault = QtWidgets.QAction(GraphWindow)
        self.actionDefault.setCheckable(True)
        self.actionDefault.setChecked(True)
        self.actionDefault.setObjectName("actionDefault")
        self.actionAdd_Title = QtWidgets.QAction(GraphWindow)
        self.actionAdd_Title.setObjectName("actionAdd_Title")
        self.actionX_Axis_Label = QtWidgets.QAction(GraphWindow)
        self.actionX_Axis_Label.setObjectName("actionX_Axis_Label")
        self.actionY_Axis_Label = QtWidgets.QAction(GraphWindow)
        self.actionY_Axis_Label.setObjectName("actionY_Axis_Label")
        self.actionVFT_Plot = QtWidgets.QAction(GraphWindow)
        self.actionVFT_Plot.setObjectName("actionVFT_Plot")
        self.actionAll_Black = QtWidgets.QAction(GraphWindow)
        self.actionAll_Black.setObjectName("actionAll_Black")
        self.toolBar.addAction(self.actionPlot)
        self.toolBar.addAction(self.actionVFT_Plot)
        self.toolBar.addAction(self.actionFit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLimiter)
        self.toolBar.addAction(self.actionClipper)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClip)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear)
        self.menuGraph.addAction(self.actionDielectric)
        self.menuGraph.addAction(self.actionVFT_Arrhenius)
        self.menuGraph.addSeparator()
        self.menuView.addAction(self.actionAll_Black)
        self.menuMode.addAction(self.actionDefault)
        self.menuMode.addAction(self.actionSelected_Only)
        self.menuBar.addAction(self.menuGraph.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuMode.menuAction())

        self.retranslateUi(GraphWindow)
        QtCore.QMetaObject.connectSlotsByName(GraphWindow)

    def retranslateUi(self, GraphWindow):
        _translate = QtCore.QCoreApplication.translate
        GraphWindow.setWindowTitle(_translate("GraphWindow", "MainWindow"))
        self.label_2.setText(_translate("GraphWindow", "Temp:"))
        self.label.setText(_translate("GraphWindow", "Run:"))
        self.toolBar.setWindowTitle(_translate("GraphWindow", "toolBar"))
        self.menuGraph.setTitle(_translate("GraphWindow", "Graph"))
        self.menuView.setTitle(_translate("GraphWindow", "View"))
        self.menuMode.setTitle(_translate("GraphWindow", "Mode"))
        self.actionFit.setText(_translate("GraphWindow", "Fit"))
        self.actionFit.setShortcut(_translate("GraphWindow", "F"))
        self.actionPlot.setText(_translate("GraphWindow", "Plot"))
        self.actionLimiter.setText(_translate("GraphWindow", "Limter"))
        self.actionLimiter.setShortcut(_translate("GraphWindow", "A"))
        self.actionClipper.setText(_translate("GraphWindow", "Clipper"))
        self.actionClip.setText(_translate("GraphWindow", "Clip"))
        self.actionDielectric.setText(_translate("GraphWindow", "Dielectric"))
        self.actionVFT_Arrhenius.setText(_translate("GraphWindow", "VFT/Arrhenius"))
        self.actionClear.setText(_translate("GraphWindow", "Clear"))
        self.actionSelected_Only.setText(_translate("GraphWindow", "Selected Only"))
        self.actionSelected_Only.setShortcut(_translate("GraphWindow", "S"))
        self.actionDefault.setText(_translate("GraphWindow", "Default"))
        self.actionAdd_Title.setText(_translate("GraphWindow", "Graph Title"))
        self.actionX_Axis_Label.setText(_translate("GraphWindow", "X Axis Label"))
        self.actionY_Axis_Label.setText(_translate("GraphWindow", "Y Axis Label"))
        self.actionVFT_Plot.setText(_translate("GraphWindow", "VFT Plot"))
        self.actionAll_Black.setText(_translate("GraphWindow", "All Black"))
        self.actionAll_Black.setShortcut(_translate("GraphWindow", "Ctrl+Q"))
from customgraph import CustomGraph


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GraphWindow = QtWidgets.QMainWindow()
    ui = Ui_GraphWindow()
    ui.setupUi(GraphWindow)
    GraphWindow.show()
    sys.exit(app.exec_())
