from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1005, 765)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/icons8-graph-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setAcceptDrops(True)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setViewMode(QtWidgets.QMdiArea.SubWindowView)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(225, 0))
        self.frame.setMaximumSize(QtCore.QSize(225, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CustomTree = CustomTree(self.frame)
        self.CustomTree.setEnabled(True)
        self.CustomTree.setMinimumSize(QtCore.QSize(225, 0))
        self.CustomTree.setMaximumSize(QtCore.QSize(225, 16777215))
        self.CustomTree.setAcceptDrops(True)
        self.CustomTree.setDragEnabled(True)
        self.CustomTree.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.CustomTree.setDefaultDropAction(QtCore.Qt.ActionMask)
        self.CustomTree.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.CustomTree.setIndentation(10)
        self.CustomTree.setHeaderHidden(True)
        self.CustomTree.setObjectName("CustomTree")
        item_0 = QtWidgets.QTreeWidgetItem(self.CustomTree)
        self.CustomTree.topLevelItem(0).setText(0, "project")
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item_0.setFont(0, font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/folder2_29391.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("../icons/folder_open_29392.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("../icons/folder_open_29392.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("../icons/folder_open_29392.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        item_0.setIcon(0, icon1)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/folder2_29391.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("../icons/folder_open_29392.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap("../icons/folder_open_29392.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        item_1.setIcon(0, icon2)
        self.CustomTree.header().setVisible(False)
        self.gridLayout_2.addWidget(self.CustomTree, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.graphSettingsTab = QtWidgets.QWidget()
        self.graphSettingsTab.setAutoFillBackground(False)
        self.graphSettingsTab.setObjectName("graphSettingsTab")
        self.frame_3 = QtWidgets.QFrame(self.graphSettingsTab)
        self.frame_3.setGeometry(QtCore.QRect(0, 60, 221, 71))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.xAxisComboBox = QtWidgets.QComboBox(self.frame_3)
        self.xAxisComboBox.setDuplicatesEnabled(True)
        self.xAxisComboBox.setObjectName("xAxisComboBox")
        self.xAxisComboBox.addItem("")
        self.xAxisComboBox.addItem("")
        self.gridLayout_4.addWidget(self.xAxisComboBox, 1, 0, 1, 1)
        self.xAxisLabel = QtWidgets.QLabel(self.frame_3)
        self.xAxisLabel.setObjectName("xAxisLabel")
        self.gridLayout_4.addWidget(self.xAxisLabel, 0, 0, 1, 1)
        self.yAxisLabel = QtWidgets.QLabel(self.frame_3)
        self.yAxisLabel.setObjectName("yAxisLabel")
        self.gridLayout_4.addWidget(self.yAxisLabel, 0, 1, 1, 1)
        self.yAxisComboBox = QtWidgets.QComboBox(self.frame_3)
        self.yAxisComboBox.setDuplicatesEnabled(True)
        self.yAxisComboBox.setObjectName("yAxisComboBox")
        self.yAxisComboBox.addItem("")
        self.yAxisComboBox.addItem("")
        self.gridLayout_4.addWidget(self.yAxisComboBox, 1, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.graphSettingsTab)
        self.frame_4.setGeometry(QtCore.QRect(0, 130, 221, 161))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(12, 108, 74, 16))
        self.label_6.setObjectName("label_6")
        self.titleLineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.titleLineEdit.setGeometry(QtCore.QRect(12, 35, 151, 18))
        self.titleLineEdit.setObjectName("titleLineEdit")
        self.xAxisSetLabel = QtWidgets.QLabel(self.frame_4)
        self.xAxisSetLabel.setGeometry(QtCore.QRect(12, 60, 75, 16))
        self.xAxisSetLabel.setObjectName("xAxisSetLabel")
        self.titleLabel = QtWidgets.QLabel(self.frame_4)
        self.titleLabel.setGeometry(QtCore.QRect(12, 12, 30, 16))
        self.titleLabel.setObjectName("titleLabel")
        self.xAxisLineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.xAxisLineEdit.setGeometry(QtCore.QRect(12, 83, 151, 18))
        self.xAxisLineEdit.setObjectName("xAxisLineEdit")
        self.yAxisLineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.yAxisLineEdit.setGeometry(QtCore.QRect(12, 131, 151, 18))
        self.yAxisLineEdit.setObjectName("yAxisLineEdit")
        self.titleSpinBox = QtWidgets.QSpinBox(self.frame_4)
        self.titleSpinBox.setGeometry(QtCore.QRect(167, 35, 42, 18))
        self.titleSpinBox.setProperty("value", 12)
        self.titleSpinBox.setObjectName("titleSpinBox")
        self.xAxisSpinBox = QtWidgets.QSpinBox(self.frame_4)
        self.xAxisSpinBox.setGeometry(QtCore.QRect(167, 83, 42, 18))
        self.xAxisSpinBox.setProperty("value", 28)
        self.xAxisSpinBox.setObjectName("xAxisSpinBox")
        self.yAxisSpinBox = QtWidgets.QSpinBox(self.frame_4)
        self.yAxisSpinBox.setGeometry(QtCore.QRect(167, 131, 42, 18))
        self.yAxisSpinBox.setProperty("value", 28)
        self.yAxisSpinBox.setObjectName("yAxisSpinBox")
        self.frame_5 = QtWidgets.QFrame(self.graphSettingsTab)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 221, 71))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.xAxisDropComboBox = QtWidgets.QComboBox(self.frame_5)
        self.xAxisDropComboBox.setDuplicatesEnabled(True)
        self.xAxisDropComboBox.setObjectName("xAxisDropComboBox")
        self.xAxisDropComboBox.addItem("")
        self.xAxisDropComboBox.addItem("")
        self.xAxisDropComboBox.addItem("")
        self.gridLayout_5.addWidget(self.xAxisDropComboBox, 1, 0, 1, 1)
        self.xAxisLabel_2 = QtWidgets.QLabel(self.frame_5)
        self.xAxisLabel_2.setObjectName("xAxisLabel_2")
        self.gridLayout_5.addWidget(self.xAxisLabel_2, 0, 0, 1, 1)
        self.yAxisLabel_2 = QtWidgets.QLabel(self.frame_5)
        self.yAxisLabel_2.setObjectName("yAxisLabel_2")
        self.gridLayout_5.addWidget(self.yAxisLabel_2, 0, 1, 1, 1)
        self.yAxisDropComboBox = QtWidgets.QComboBox(self.frame_5)
        self.yAxisDropComboBox.setDuplicatesEnabled(True)
        self.yAxisDropComboBox.setObjectName("yAxisDropComboBox")
        self.yAxisDropComboBox.addItem("")
        self.yAxisDropComboBox.addItem("")
        self.yAxisDropComboBox.addItem("")
        self.gridLayout_5.addWidget(self.yAxisDropComboBox, 1, 1, 1, 1)
        self.tabWidget.addTab(self.graphSettingsTab, "")
        self.viewTab = QtWidgets.QWidget()
        self.viewTab.setAutoFillBackground(False)
        self.viewTab.setObjectName("viewTab")
        self.label = QtWidgets.QLabel(self.viewTab)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.viewTab)
        self.frame_2.setGeometry(QtCore.QRect(5, 24, 201, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(11, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.blue = QtWidgets.QPushButton(self.frame_2)
        self.blue.setAutoFillBackground(False)
        self.blue.setStyleSheet("background-color: rgb(0,0,255);")
        self.blue.setText("")
        self.blue.setDefault(False)
        self.blue.setFlat(False)
        self.blue.setObjectName("blue")
        self.gridLayout_3.addWidget(self.blue, 1, 8, 1, 1)
        self.green = QtWidgets.QPushButton(self.frame_2)
        self.green.setAutoFillBackground(False)
        self.green.setStyleSheet("background-color: rgb(0, 128, 0);")
        self.green.setText("")
        self.green.setDefault(False)
        self.green.setFlat(False)
        self.green.setObjectName("green")
        self.gridLayout_3.addWidget(self.green, 0, 12, 1, 1)
        self.navy = QtWidgets.QPushButton(self.frame_2)
        self.navy.setAutoFillBackground(False)
        self.navy.setStyleSheet("background-color: rgb(0, 0, 128);")
        self.navy.setText("")
        self.navy.setDefault(False)
        self.navy.setFlat(False)
        self.navy.setObjectName("navy")
        self.gridLayout_3.addWidget(self.navy, 1, 6, 1, 1)
        self.pink = QtWidgets.QPushButton(self.frame_2)
        self.pink.setAutoFillBackground(False)
        self.pink.setStyleSheet("background-color: rgb(253,0,200);")
        self.pink.setText("")
        self.pink.setDefault(False)
        self.pink.setFlat(False)
        self.pink.setObjectName("pink")
        self.gridLayout_3.addWidget(self.pink, 1, 10, 1, 1)
        self.purple = QtWidgets.QPushButton(self.frame_2)
        self.purple.setAutoFillBackground(False)
        self.purple.setStyleSheet("background-color: rgb(171, 0, 255);")
        self.purple.setText("")
        self.purple.setDefault(False)
        self.purple.setFlat(False)
        self.purple.setObjectName("purple")
        self.gridLayout_3.addWidget(self.purple, 1, 9, 1, 1)
        self.black = QtWidgets.QPushButton(self.frame_2)
        self.black.setAutoFillBackground(False)
        self.black.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.black.setText("")
        self.black.setDefault(False)
        self.black.setFlat(False)
        self.black.setObjectName("black")
        self.gridLayout_3.addWidget(self.black, 0, 0, 1, 1)
        self.lime = QtWidgets.QPushButton(self.frame_2)
        self.lime.setAutoFillBackground(False)
        self.lime.setStyleSheet("background-color: rgb(0, 200, 0);")
        self.lime.setText("")
        self.lime.setDefault(False)
        self.lime.setFlat(False)
        self.lime.setObjectName("lime")
        self.gridLayout_3.addWidget(self.lime, 1, 0, 1, 1)
        self.aqua = QtWidgets.QPushButton(self.frame_2)
        self.aqua.setAutoFillBackground(False)
        self.aqua.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.aqua.setText("")
        self.aqua.setDefault(False)
        self.aqua.setFlat(False)
        self.aqua.setObjectName("aqua")
        self.gridLayout_3.addWidget(self.aqua, 1, 2, 1, 1)
        self.teal = QtWidgets.QPushButton(self.frame_2)
        self.teal.setAutoFillBackground(False)
        self.teal.setStyleSheet("background-color: rgb(0, 128, 128);")
        self.teal.setText("")
        self.teal.setDefault(False)
        self.teal.setFlat(False)
        self.teal.setObjectName("teal")
        self.gridLayout_3.addWidget(self.teal, 1, 1, 1, 1)
        self.crimson = QtWidgets.QPushButton(self.frame_2)
        self.crimson.setAutoFillBackground(False)
        self.crimson.setStyleSheet("background-color: rgb(220, 20, 60);")
        self.crimson.setText("")
        self.crimson.setDefault(False)
        self.crimson.setFlat(False)
        self.crimson.setObjectName("crimson")
        self.gridLayout_3.addWidget(self.crimson, 1, 12, 1, 1)
        self.gray = QtWidgets.QPushButton(self.frame_2)
        self.gray.setAutoFillBackground(False)
        self.gray.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.gray.setText("")
        self.gray.setDefault(False)
        self.gray.setFlat(False)
        self.gray.setObjectName("gray")
        self.gridLayout_3.addWidget(self.gray, 0, 1, 1, 1)
        self.maroon = QtWidgets.QPushButton(self.frame_2)
        self.maroon.setAutoFillBackground(False)
        self.maroon.setStyleSheet("background-color: rgb(128, 0, 0);")
        self.maroon.setText("")
        self.maroon.setDefault(False)
        self.maroon.setFlat(False)
        self.maroon.setObjectName("maroon")
        self.gridLayout_3.addWidget(self.maroon, 0, 2, 1, 1)
        self.red = QtWidgets.QPushButton(self.frame_2)
        self.red.setAutoFillBackground(False)
        self.red.setStyleSheet("background-color: rgb(255,0,0);")
        self.red.setText("")
        self.red.setDefault(False)
        self.red.setFlat(False)
        self.red.setObjectName("red")
        self.gridLayout_3.addWidget(self.red, 0, 6, 1, 1)
        self.orange = QtWidgets.QPushButton(self.frame_2)
        self.orange.setAutoFillBackground(False)
        self.orange.setStyleSheet("background-color: rgb(255, 165, 0);")
        self.orange.setText("")
        self.orange.setDefault(False)
        self.orange.setFlat(False)
        self.orange.setObjectName("orange")
        self.gridLayout_3.addWidget(self.orange, 0, 8, 1, 1)
        self.yellow = QtWidgets.QPushButton(self.frame_2)
        self.yellow.setAutoFillBackground(False)
        self.yellow.setStyleSheet("background-color: rgb(210, 210, 0);")
        self.yellow.setText("")
        self.yellow.setDefault(False)
        self.yellow.setFlat(False)
        self.yellow.setObjectName("yellow")
        self.gridLayout_3.addWidget(self.yellow, 0, 9, 1, 1)
        self.olive = QtWidgets.QPushButton(self.frame_2)
        self.olive.setAutoFillBackground(False)
        self.olive.setStyleSheet("background-color: rgb(128, 128, 0);")
        self.olive.setText("")
        self.olive.setDefault(False)
        self.olive.setFlat(False)
        self.olive.setObjectName("olive")
        self.gridLayout_3.addWidget(self.olive, 0, 10, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.viewTab)
        self.label_2.setGeometry(QtCore.QRect(10, 103, 55, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.viewTab)
        self.comboBox.setGeometry(QtCore.QRect(70, 100, 131, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.viewTab)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(self.viewTab)
        self.spinBox.setGeometry(QtCore.QRect(100, 139, 97, 22))
        self.spinBox.setProperty("value", 4)
        self.spinBox.setObjectName("spinBox")
        self.label_4 = QtWidgets.QLabel(self.viewTab)
        self.label_4.setGeometry(QtCore.QRect(10, 177, 91, 10))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineSpinBox = QtWidgets.QSpinBox(self.viewTab)
        self.lineSpinBox.setGeometry(QtCore.QRect(100, 171, 97, 22))
        self.lineSpinBox.setProperty("value", 1)
        self.lineSpinBox.setObjectName("lineSpinBox")
        self.label_5 = QtWidgets.QLabel(self.viewTab)
        self.label_5.setGeometry(QtCore.QRect(10, 205, 91, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.legendCheckBox = QtWidgets.QCheckBox(self.viewTab)
        self.legendCheckBox.setGeometry(QtCore.QRect(108, 205, 21, 20))
        self.legendCheckBox.setText("")
        self.legendCheckBox.setChecked(True)
        self.legendCheckBox.setObjectName("legendCheckBox")
        self.label_7 = QtWidgets.QLabel(self.viewTab)
        self.label_7.setGeometry(QtCore.QRect(10, 230, 91, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.symbolCheckBox = QtWidgets.QCheckBox(self.viewTab)
        self.symbolCheckBox.setGeometry(QtCore.QRect(108, 232, 21, 20))
        self.symbolCheckBox.setText("")
        self.symbolCheckBox.setChecked(True)
        self.symbolCheckBox.setObjectName("symbolCheckBox")
        self.tabWidget.addTab(self.viewTab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1005, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuFits = QtWidgets.QMenu(self.menubar)
        self.menuFits.setObjectName("menuFits")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.toolBar.setFont(font)
        self.toolBar.setStatusTip("")
        self.toolBar.setIconSize(QtCore.QSize(25, 25))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/document_29383.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Project.setIcon(icon3)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionGraph_2 = QtWidgets.QAction(MainWindow)
        self.actionGraph_2.setObjectName("actionGraph_2")
        self.actionNew_Sheet = QtWidgets.QAction(MainWindow)
        self.actionNew_Sheet.setObjectName("actionNew_Sheet")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionUndo_Redo = QtWidgets.QAction(MainWindow)
        self.actionUndo_Redo.setObjectName("actionUndo_Redo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionToolbar = QtWidgets.QAction(MainWindow)
        self.actionToolbar.setCheckable(True)
        self.actionToolbar.setChecked(True)
        self.actionToolbar.setObjectName("actionToolbar")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/diskette_29382.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon4)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/folder2_29391.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon5)
        self.actionOpen.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setIcon(icon3)
        self.actionNew.setObjectName("actionNew")
        self.actionImport_Data = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../icons/add_29356.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport_Data.setIcon(icon6)
        self.actionImport_Data.setObjectName("actionImport_Data")
        self.actionSheet = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../icons/new_sheet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSheet.setIcon(icon7)
        self.actionSheet.setObjectName("actionSheet")
        self.actionGraph = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../icons/new_graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGraph.setIcon(icon8)
        self.actionGraph.setObjectName("actionGraph")
        self.actionMake_CSV = QtWidgets.QAction(MainWindow)
        self.actionMake_CSV.setObjectName("actionMake_CSV")
        self.actionSort_Sheets = QtWidgets.QAction(MainWindow)
        self.actionSort_Sheets.setObjectName("actionSort_Sheets")
        self.actionSave_VFT_Dict_As = QtWidgets.QAction(MainWindow)
        self.actionSave_VFT_Dict_As.setObjectName("actionSave_VFT_Dict_As")
        self.actionOpen_VFT_Dict = QtWidgets.QAction(MainWindow)
        self.actionOpen_VFT_Dict.setObjectName("actionOpen_VFT_Dict")
        self.actionAdd_Dictionary = QtWidgets.QAction(MainWindow)
        self.actionAdd_Dictionary.setObjectName("actionAdd_Dictionary")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionMake_CSV)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionGraph)
        self.menuFile.addAction(self.actionSheet)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_VFT_Dict_As)
        self.menuFile.addAction(self.actionOpen_VFT_Dict)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo_Redo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuView.addAction(self.actionToolbar)
        self.menuFits.addAction(self.actionSort_Sheets)
        self.menuFits.addAction(self.actionAdd_Dictionary)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuFits.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSheet)
        self.toolBar.addAction(self.actionGraph)
        self.toolBar.addAction(self.actionAdd_Dictionary)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.yAxisDropComboBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LSGraph"))
        self.CustomTree.setSortingEnabled(False)
        self.CustomTree.headerItem().setText(0, _translate("MainWindow", "Loaded Files"))
        __sortingEnabled = self.CustomTree.isSortingEnabled()
        self.CustomTree.setSortingEnabled(False)
        self.CustomTree.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "sheets"))
        self.CustomTree.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "graphs"))
        self.CustomTree.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "fit values"))
        self.CustomTree.setSortingEnabled(__sortingEnabled)
        self.xAxisComboBox.setItemText(0, _translate("MainWindow", "log10"))
        self.xAxisComboBox.setItemText(1, _translate("MainWindow", "no scaling"))
        self.xAxisLabel.setText(_translate("MainWindow", "X-Axis Scaling:"))
        self.yAxisLabel.setText(_translate("MainWindow", "Y-Axis Scaling:"))
        self.yAxisComboBox.setItemText(0, _translate("MainWindow", "log10"))
        self.yAxisComboBox.setItemText(1, _translate("MainWindow", "no scaling"))
        self.label_6.setText(_translate("MainWindow", "Y-Axis Label:"))
        self.xAxisSetLabel.setText(_translate("MainWindow", "X-Axis Label:"))
        self.titleLabel.setText(_translate("MainWindow", "Title:"))
        self.xAxisDropComboBox.setItemText(0, _translate("MainWindow", "frq"))
        self.xAxisDropComboBox.setItemText(1, _translate("MainWindow", "eps\'"))
        self.xAxisDropComboBox.setItemText(2, _translate("MainWindow", "eps\'\'"))
        self.xAxisLabel_2.setText(_translate("MainWindow", "X-Axis:"))
        self.yAxisLabel_2.setText(_translate("MainWindow", "Y-Axis:"))
        self.yAxisDropComboBox.setItemText(0, _translate("MainWindow", "frq"))
        self.yAxisDropComboBox.setItemText(1, _translate("MainWindow", "eps\'"))
        self.yAxisDropComboBox.setItemText(2, _translate("MainWindow", "eps\'\'"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.graphSettingsTab), _translate("MainWindow", "Graph Settings"))
        self.label.setText(_translate("MainWindow", "Colour:"))
        self.label_2.setText(_translate("MainWindow", "Symbol:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Circle"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Square"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Triangle"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Star"))
        self.comboBox.setItemText(4, _translate("MainWindow", "+"))
        self.comboBox.setItemText(5, _translate("MainWindow", "x"))
        self.label_3.setText(_translate("MainWindow", "Symbol Size:"))
        self.label_4.setText(_translate("MainWindow", "Line Width:"))
        self.label_5.setText(_translate("MainWindow", "Show Legend:"))
        self.label_7.setText(_translate("MainWindow", "Show Symbol:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.viewTab), _translate("MainWindow", "Graph View"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuFits.setTitle(_translate("MainWindow", "Data"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
        self.actionGraph_2.setText(_translate("MainWindow", "New Graph "))
        self.actionNew_Sheet.setText(_translate("MainWindow", "New Sheet"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionUndo.setText(_translate("MainWindow", "Copy"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionUndo_Redo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionToolbar.setText(_translate("MainWindow", "Toolbar"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "open lsgraph project..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionImport_Data.setText(_translate("MainWindow", "Import Data"))
        self.actionSheet.setText(_translate("MainWindow", "Sheet"))
        self.actionGraph.setText(_translate("MainWindow", "Graph"))
        self.actionMake_CSV.setText(_translate("MainWindow", "Make CSV"))
        self.actionSort_Sheets.setText(_translate("MainWindow", "Sort Sheets"))
        self.actionSave_VFT_Dict_As.setText(_translate("MainWindow", "Save VFT Dict as..."))
        self.actionOpen_VFT_Dict.setText(_translate("MainWindow", "Open VFT Dict"))
        self.actionAdd_Dictionary.setText(_translate("MainWindow", "Add Dictionary"))
from customtree import CustomTree


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
